Install vcpython27 when python.version is 2.7
This commit installs vcpython27 when the python version is 2.7 because
an error occurs without it like this.

 error: Microsoft Visual C++ 9.0 is required. Get it from
        http://aka.ms/vcpython27